[package]
name = "minigrep_vbomfim"
license = "MIT OR Apache-2.0"
description = "A simple grep tool written in Rust"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }

[dev-dependencies]
serial_test = "3.2.0"
